// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Document {
    "version": number;
    "profile": Profile;
    "schema": Schema;
    "progress": { [_ in string]?: number } | null;
}

export interface Group {
    "id": string;
    "name": string;
    "color": string;
    "tracks": Track[] | null;
}

export interface Level {
    "name": string;
    "description": string;
    "examples": string[] | null;
}

export interface Profile {
    "name": string;
    "role": string;
}

export interface Schema {
    "name": string;
    "groups": Group[] | null;
}

export interface Track {
    "id": string;
    "code": string;
    "name": string;
    "description": string;
    "levels": Level[] | null;
}
