// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as career$0 from "./internal/career/models.js";

/**
 * Export writes the latest committed document; false means dialog cancellation.
 */
export function Export(): $CancellablePromise<boolean> {
    return $Call.ByID(4172634573);
}

/**
 * Import replaces the saved document only after the selected file is validated.
 * A nil document means that the user cancelled the native file dialog.
 */
export function Import(): $CancellablePromise<career$0.Document | null> {
    return $Call.ByID(1968021102);
}

export function Load(): $CancellablePromise<career$0.Document> {
    return $Call.ByID(97939127);
}

export function Save(document: career$0.Document): $CancellablePromise<career$0.Document> {
    return $Call.ByID(2778773226, document);
}
